### ISSUE TITLE
Why GCC

### ISSUE THREAD

**Issue by Naville** [kclkcl/pendual-enabler#1]
I don't play HDD.Just asking.
Why we need GCC for windows specific game patching

**Comment by ar-nim** [comment]
GCC requires no dependency, I don't want to spend gigabytes just for Visual
C++. It's easy to get GCC on Windows, just get TDM-GCC. Besides, GCC is
cross platform.

Probably the only thing that needs to be modified when compiling on another
OS is system("cls"), it's portable enough.
